export const otherTasks = [{
  title: "limpiar",
  description: "la habitación",
  status: "done",
  difficulty: "easy",
  createdAt: new Date(),
  updatedAt: new Date(),
  dueDate: new Date("12/7/2025"),
},
{
  title: "cocinar",
  description: "pollo al disco",
  status: "to do",
  difficulty: "easy",
  createdAt: new Date(),
  updatedAt: new Date(),
  dueDate: new Date("1/5/2026"),
},
{
  title: "programar",
  description: "la tarea de paradigmas",
  status: "in progress",
  difficulty: "easy",
  createdAt: new Date(),
  updatedAt: new Date(),
  dueDate: new Date("10/30/2025"),
},
{
  title: "terminar práctico",
  description: "de física",
  status: "done",
  difficulty: "medium",
  createdAt: new Date(),
  updatedAt: new Date(),
  dueDate: new Date("11/2/2025"),
},
{
  title: "ver partido",
  description: "argentina vs ecuador",
  status: "to do",
  difficulty: "easy",
  createdAt: new Date(),
  updatedAt: new Date(),
  dueDate: new Date("10/20/2025"),
}];
